version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "cfn-lint"
type = "community"

[[analyzers]]
name = "javascript"
  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "vitest",
    "jest",
    "typescript"
  ]

[[analyzers]]
name = "typescript"

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "standardjs"

[[code_formatters]]
name = "eslint"
